### ISSUE TITLE
angular-auth-oidc-client =>  angular-oauth2-oidc

### ISSUE THREAD

**Issue by paqogomez** [robisim74/angular-openid-connect-php#3]
I've been following your thread over on auto login here: 
https://github.com/damienbod/angular-auth-oidc-client/issues/104

I have been using angular-oath2-oidc and have been frustrated with it, so I was looking to change using your examples, (I too want to simply login first, no login click) only to find that you have switched to what I am already using.  lol

Can you explain why you switched off of angular-auth-oidc-client?

Thanks

**Comment by robisim74** [comment]
Hi @paqogomez,

the sample that uses _angular-auth-oidc-client_ is still in this repo, see this branch: https://github.com/robisim74/angular-openid-connect-php/tree/angular-auth-oidc-client

There are two certified library by OpenId for Angular: so I created an example for each one.

I do not know what problems you found with the _angular-oauth2-oidc_: I personally have not found any problem in implementing both. Then there are of course different behaviors in each of the two depending on the situation.

About the auto-login: the best solution is to delegate the request to a component (for example in OnInit hook) to avoid weird behavior in the Angular app, and then return to a specific component.

Greetings
