### ISSUE TITLE
Update angular-auth-oidc-client

### ISSUE THREAD

**Issue by rajguru827** [robisim74/angular-openid-connect-php#4]
Please update the code to latest angular-auth-oidc-client.

**Comment by robisim74** [comment]
This is not a course or a starter: it's just an example, whose main goal is to show how OpenId connect implicit flow works between an Angular client and a PHP server.

If you have problems updating a specific library, you should contact the repository of that library.

If you want to contribute to this project, feel free to do a pr.

Greetings

**Comment by rajguru827** [comment]
thanks @robisim74
